name: Deploy app

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com

on:
  push:
    branches:
      - dev

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create CNAME file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "public/CNAME"
          FILE_DATA: "audiomotion.app"
      - name: Run shell script
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git mv docs public
          git commit -m "Move docs folder into public folder"
          git subtree split --prefix public -b gh-pages
          git push -f origin gh-pages:gh-pages
