name: Deploy app

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com

on:
  push:
    branches:
      - dev

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create files
          run: |
            echo "audiomotion.app" > public/CNAME
            echo -e "include: [\".well-known\"]\n" > public/_config.yml
            echo -e "This is a Brave Creators publisher verification file.\n\nDomain: audiomotion.app\nToken: ddbc4cddcf21685fd67a05d53d95d4f420f67190cb38ec7b6250e3fb8cb7d6cf\n" > public/.well-known/brave-rewards-verification.txt
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: public/music
      - uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: public/backgrounds
      - name: Run shell script
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git mv docs public
          git add .
          git commit -m "Deploy app"
          git subtree split --prefix public -b gh-pages
          git push -f origin gh-pages:gh-pages
