name: Deploy app

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com

on:
  push:
    branches:
      - dev

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create CNAME file
        uses: 1arp/create-a-file-action@0.4.4
        with:
          path: 'public'
          isAbsolutePath: false
          file: 'CNAME'
          content: 'audiomotion.app'
      - name: Run shell script
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git mv docs public
          git commit -m "Move docs folder into public folder"
          git subtree split --prefix public -b gh-pages
          git push -f origin gh-pages:gh-pages
