name: Deploy app

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com

on:
  push:
    branches:
      - dev

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run shell script
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git mv docs public
          git commit -m "Move docs folder into public folder"
          git subtree split --prefix public -b gh-pages
          git push -f origin gh-pages:gh-pages
      - name: Create CNAME file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'CNAME'
          branch: 'gh-pages'
          message: 'Create CNAME file'
          file_content: 'audiomotion.app'
