name: Deploy app

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com

on:
  push:
    branches:
      - dev

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create CNAME file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "public/CNAME"
          FILE_DATA: "audiomotion.app"
      - name: Create _config.yml file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "public/_config.yml"
          FILE_DATA: 'include: [".well-known"]'
      - name: Create brave-rewards-verification.txt file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "public/.well-known/brave-rewards-verification.txt"
          FILE_DATA: |
            This is a Brave Creators publisher verification file.

            Domain: audiomotion.app
            Token: ddbc4cddcf21685fd67a05d53d95d4f420f67190cb38ec7b6250e3fb8cb7d6cf
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: public/music
      - uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: public/backgrounds
      - name: Run shell script
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git mv docs public
          git add .
          git commit -m "Deploy app"
          git subtree split --prefix public -b gh-pages
          git push -f origin gh-pages:gh-pages
